### ISSUE TITLE
Infer on larger tiles to handle edge effects coming from the model

### ISSUE THREAD

**Issue by srmsoumya** [developmentseed/pearl-backend#49]
Current model gets confused with the polygon classes when it is looking at smaller regions (256 x 256 chips) as it is not aware of the surrounding and creates weird edge effects as output, please check the details here: https://github.com/developmentseed/pearl-backend/issues/34#issuecomment-1465900304

This can be addressed by passing larger tiles as input to the model, i.e 512x512 or 1024x1024 or 2048x2048. @ingalls & @geohacker you can take a call on the payload size & tolerance for edge effects coming from the model.

cc' @developmentseed/pearl

**Comment by geohacker** [comment]
@srmsoumya I'm starting to think that this won't be a trivial change to make. We make the 256x256 assumption in a lot of places across the code base. And since this is specific to the Mexico models, we'll need to parametrize this properly. @ingalls what do you think?

**Comment by ingalls** [comment]
@geohacker I have the same gut feeling. How would you feel about time-boxing a 2hr attempt to get 512x512 chips working? Once I dive in I should have a good sense of what I start to run into.

**Comment by geohacker** [comment]
@ingalls that sounds good to me!

**Comment by srmsoumya** [comment]
yep, I think `512x512` is a good chip size for the model to make sense of the surrounding. Thanks!

**Comment by geohacker** [comment]
This is done
