### ISSUE TITLE
Increase the number of data points coming from the user for model retraining

### ISSUE THREAD

**Issue by srmsoumya** [developmentseed/pearl-backend#50]
For our current baseline model, we are creating a seed dataset of size 16000 embeddings. While fixing the model prediction or adding new classes, we randomly pick 100 points from the polygon drawn by the user.
Model retraining is then done by stack these 100 pixel embeddings with the seed dataset. It takes multiple iteration to lear these features because of size mismatch - Increase this to a larger number like 300-400 to see an improvement in model retraining speed.

I can work on some experiments to understand what is a good size for both seed-dataset & number of points for new embeddings. In the mean time, we can just increase the number of points coming from the user.

cc' @developmentseed/pearl

**Comment by geohacker** [comment]
It looks like to me that we are currently only taking 50 points https://github.com/developmentseed/pearl-backend/blob/develop/services/gpu/lib/ModelSrv.py#L573. This should be easy to change. cc @ingalls

**Comment by geohacker** [comment]
I just pushed a change to make this 200 https://github.com/developmentseed/pearl-backend/pull/48/commits/a5d47f0c9b5c4a94d6b25c6d8b45dff62bf6bcbc
