### ISSUE TITLE
Check if retraining gets points from multiple polygons

### ISSUE THREAD

**Issue by srmsoumya** [developmentseed/pearl-backend#51]
This is an issue I had while testing PEARL during my sprint last year.

When a user selects multiple polygons, the front-end UI only showed points going from a single UI to the backend for model retraining - not sure if this is a frontend bug or backend bug or this has already been addressed. Creating this ticket to check our current approach.

**Comment by geohacker** [comment]
@srmsoumya do you mind outlining steps to reproduce here?

**Comment by geohacker** [comment]
I'm try now and was able to see that points from all polygons for the class was selected:

![image](https://user-images.githubusercontent.com/371666/224987506-fcb6b26d-d9c6-4fbe-af85-7adf6e2badf5.png)

So perhaps this was addressed previously 😅

**Comment by srmsoumya** [comment]
@geohacker yes, looks like it was fixed - I will close this Issue.
