### ISSUE TITLE
Cannot create timeframe share URL

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#55]
The endpoint `POST /project/:projectid/aoi/:aoiid/timeframe/:timeframeid/share` is returning 500 for all requests, with message `Failed to commit to aoi_timeframe_share`. 

cc @ingalls @geohacker

**Comment by ingalls** [comment]
The share API uses a UUID that is not marked as a primary key. This ends up with the default behavior of batch-generic attempting to update via an `id` field which does not exist, causing a failure.

I've updated the `share.commit` call in `share.upload` to specify the update column as `uuid`

**Comment by geohacker** [comment]
@ingalls @vgeorge is this fixed?

**Comment by vgeorge** [comment]
Yes, I was able to generate shares.
