### ISSUE TITLE
Unable to delete project

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#58]
I'm consistently getting 500 status while trying to delete projects.

cc @ingalls

**Comment by vgeorge** [comment]
I'm seeing this error again (500 status on DELETE). Not in all projects, but in one that failed to generate a prediction. Its id is 70 at the staging API.

**Comment by LanesGood** [comment]
@ingalls I'm also seeing this error again - in a project that did generate predictions. I'm looking at project 72 in staging API.

Console errors:

```
Warning: Failed prop type: Invalid prop `revealed` of type `string` supplied to `h`, expected `boolean`.

DELETE https://api.lulc-staging.ds.io/api/project/72 500 (Internal Server Error)
```

**Comment by ingalls** [comment]
An instance around deletion when an active instance was present was identified and fixed.
