### ISSUE TITLE
Add AOI, Timeframe and Mosaic meta to /shares endpoint

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#59]
The project profile page has the following table:

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/329694/233418503-8adbe091-ae44-45a0-b73f-9bdb01dd8e49.png">

On version 1 (without timeframes), the table is built by querying bookmarked AOIs at endpoint `/project/:id/aoi`, which returned a paginated list of AOIs with `shares` property that contained an array of shares meta in reverse chronological order.

On version 2 (with timeframes), fetching the shares directly at `project/:id/share` will be necessary because they are related to Timeframes and not AOIs. This would avoid multiple fetch calls to build the table, which should contain the existing columns and the mosaic name. 

If this approach makes sense, we need to:

- Replace `aoi_id` property with AOI meta
- Replace `timeframe_id` property with Timeframe meta
- Include mosaic meta as a `mosaic` property or as a Timeframe property

cc @geohacker @ingalls

**Comment by ingalls** [comment]
- `mosaic` is now an object returned via any of the TimeFrame endpoints
- The Share endpoint returns an object for `aoi`, & `timeframe`

**Comment by vgeorge** [comment]
@ingalls it looks like the `GET project/:id/share` endpoint is not returning AOI and timeframe object. This is a response I just got from the staging API:

```json
{
  "total": 2,
  "shares": [
    {
      "uuid": "59229757-254c-418c-8bd0-296807072617",
      "aoi_id": 9,
      "timeframe_id": 20,
      "created": 1682681920310,
      "storage": true
    },
    {
      "uuid": "21f7dd48-59c3-45cd-adbc-8a5da655ff54",
      "aoi_id": 3,
      "timeframe_id": 3,
      "created": 1682519815483,
      "storage": true
    }
  ],
  "project_id": 2
}
```

**Comment by ingalls** [comment]
Per Chat: This was due to the complicated way we implemented mosaic references to keep legacy use supported. The join is now fixed.
