### ISSUE TITLE
Failed batch prediction is not flagged as completed

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#63]
If I remember correctly, the past behaviour of the API was to flag a prediction as `completed=true` on success, error, or abort. But now I got a failed prediction when querying `GET /project/:id/batch?completed=false&order=desc`, which is used to fetch any running prediction. Here is the response:

```
{
  "total": 1,
  "batch": [
    {
      "id": 1,
      "created": 1682609954338,
      "updated": 1682610296666,
      "completed": false,
      "error": "Processing Error: DataLoader worker (pid(s) 11) exited unexpectedly",
      "aoi": 7
    }
  ]
}
```

If this is not a regression we will need to create a new 'running' flag.

cc @ingalls @geohacker

**Comment by ingalls** [comment]
Per chat: The presence of the `error` field implies that the batch is "done" but did not complete successfully.
