### ISSUE TITLE
Add POST /mosaic

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#72]
To enable [Multiple Imagery Selection](https://github.com/developmentseed/pearl-frontend/issues/22#issuecomment-1878546316) the API should have a route to create mosaics, using Planetary Supercomputer as a source.

@geohacker pointed out that the parameters to be passed in the request can be the same used in the script [create_sentinel_mosaic.py](https://github.com/developmentseed/pearl-backend/blob/project-ts/helpers/create_sentinel_mosaic.py).

**Comment by vgeorge** [comment]
I tried to create a new mosaic by doing a `POST /mosaic` request with the following payload:

```
{
  "params": {
    "assets": ["B04", "B03", "B02", "B08"],
    "rescale": "0,10000",
    "collection": "sentinel-2-l2a"
  },
  "imagery_source_id": 2,
  "ui_params": {
    "assets": ["B04", "B03", "B02"],
    "collection": "sentinel-2-l2a",
    "color_formula": "Gamma+RGB+3.2+Saturation+0.8+Sigmoidal+RGB+25+0.35"
  },
  "name": "Sentinel-2 2023-07-03",
  "mosaic_ts_start": 1688342400000,
  "mosaic_ts_end": 1696118400000
}
```

But I got a response with a 500 status and the following body:

```
{"status":500,"message":"Failed to generate mosaics","messages":[]}
```

@ingalls @geohacker I'm not able to create mosaics now, would you be able to clarify if there is something wrong with the request or if there is an internal issue in the backend?

**Comment by ingalls** [comment]
Fixed, in project-ts
