### ISSUE TITLE
Add 'GET /share' endpoint

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#73]
To implement the [Compare Tool](https://github.com/developmentseed/pearl-frontend/issues/66), we need a new endpoint that lists all shares created, regardless of the project they are part of.

We will probably need some filtering, maybe by share name and mosaic id, but let's confirm first before implementing.

cc @ingalls @LanesGood @geohacker

**Comment by vgeorge** [comment]
@ingalls I'm able to make requests to the endpoint, but it doesn't include the `published` property in the response, which is needed to select maps for the compare tool.

**Comment by ingalls** [comment]
@vincentsarago All maps in the `/share` api are published, this is the criteria for inclusion. But I can add that property to the response.

**Comment by ingalls** [comment]
The `published` field is now returned in the public list shares endpoint.
