### ISSUE TITLE
Add collection id to imagery source model

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#78]
In order to fetch metadata from Planetary Computer STAC Catalog, we need to use its collection ids, but the Imagery Source model doesn't include it.  We need to add a property `collectionId` to it, which will be used to fetch metadata from the collection, like the mosaics available. Some example URLs:

https://planetarycomputer.microsoft.com/api/data/v1/mosaic/info?collection=sentinel-2-l2a
https://planetarycomputer.microsoft.com/api/data/v1/mosaic/info?collection=naip

cc @ingalls @geohacker

**Comment by ingalls** [comment]
Added in: https://github.com/developmentseed/pearl-backend/pull/38/commits/d30bdba0e7d3054353570deff9895cd9d67aa5d6
