### ISSUE TITLE
Enhance 'GET /shares' endpoint

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/pearl-backend#79]
We need to include the following properties in the response of `GET /shares` endpoint:

- `createdAt`
- `model`
- `imagerySource`
- `checkpoint`

Those are required to populate the `Public Prediction Maps` page, as suggested by @LanesGood at https://github.com/developmentseed/pearl-frontend/pull/77#issuecomment-1915577086.

cc @ingalls

**Comment by ingalls** [comment]
- [x] `createdAt`
- [x] `model`
- [x] `imagerySource`
- [x] `checkpoint`

**Comment by ingalls** [comment]
Deployed.
