### ISSUE TITLE
Add class names to geotiff

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/pearl-backend#80]
Geotiff download references classes by number. Consider addiing the name of the class as part of the GeoTIFF.

**Comment by vgeorge** [comment]
@geohacker @ingalls this looks like a backend issue, would you please confirm?

**Comment by geohacker** [comment]
Yes, we should set the band name while the geotiff is generated. @ingalls @vincentsarago I'm forgetting where the geotiff generation happens, this should be straightforward?

**Comment by vincentsarago** [comment]
https://github.com/developmentseed/pearl-backend/blob/develop/services/tiles/dynamic_tiler/endpoints/factory.py#L186 ?

**Comment by vincentsarago** [comment]
@LanesGood can you tell me exactly what the names should be?

**Comment by LanesGood** [comment]
@vincentsarago I believe they are returned by the API, as each model has base classes, and each project can add `n` arbitrary classes. 

In https://api.lulc-staging.ds.io/docs/#/TimeFrame/get_project___projectid__aoi___aoiid__timeframe___timeframeid_ you can see that each `timeframe` has a classes array:
`"classes": [
    {
      "name": "string",
      "color": "string"
    }
  ],`

The download endpoint includes the timeframeid, so I believe the classes for the geotiff should come from there.

**Comment by vincentsarago** [comment]
I'm still not sure to follow how the COG are structure and what the band names should be 🤷 

It's been a long time I haven't touch pearl 😬 

@geohacker can you help 🙏

**Comment by LanesGood** [comment]
Discussed with @vincentsarago - we will explore adding the classnames associated with pixel values in the COG json metadata, but this is not supplied to QGIS or other platforms. The partner expressed wanting to know these names in a program like QGIS, but Vincent confirmed this is not possible for pixel values. Alternatively, the COG could split each pixel value into a different band, but this would become an even more complex process and would not permit straightforward visualization of a LULC map in a single layer.

**Comment by LanesGood** [comment]
After followup with @vincentsarago we've determined this isn't a function/feature that can be enabled in geotiff creation.
